import DashboardWrapper from "./dashboardWrapper";

export const metadata = {
  title: "SkillGate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
